"""baseline

Revision ID: 1b61c6235f0f
Revises: 
Create Date: 2025-10-27 20:49:04.048596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b61c6235f0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_justificaciones_id'), table_name='justificaciones')
    op.drop_index(op.f('ix_justificaciones_user_id'), table_name='justificaciones')
    op.drop_table('justificaciones')
    op.drop_index(op.f('ix_horarios_id'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_turno_id'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_user_id'), table_name='horarios')
    op.drop_table('horarios')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_users_codigo_user'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tipo'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_user_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_turnos_id'), table_name='turnos')
    op.drop_table('turnos')
    op.drop_index(op.f('ix_asistencias_fecha'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_horario_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_user_id'), table_name='asistencias')
    op.drop_table('asistencias')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencias',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('horario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hora_entrada', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('hora_salida', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('metodo_entrada', postgresql.ENUM('HUELLA', 'MANUAL', 'FACIAL', name='metodoregistro'), autoincrement=False, nullable=True),
    sa.Column('metodo_salida', postgresql.ENUM('HUELLA', 'MANUAL', 'FACIAL', name='metodoregistro'), autoincrement=False, nullable=True),
    sa.Column('estado', postgresql.ENUM('PRESENTE', 'AUSENTE', 'TARDE', 'JUSTIFICADO', 'PERMISO', name='estadoasistencia'), autoincrement=False, nullable=False),
    sa.Column('tardanza', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('minutos_tardanza', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('horas_trabajadas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('justificacion_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], name=op.f('asistencias_horario_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['justificacion_id'], ['justificaciones.id'], name=op.f('asistencias_justificacion_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('asistencias_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('asistencias_pkey'))
    )
    op.create_index(op.f('ix_asistencias_user_id'), 'asistencias', ['user_id'], unique=False)
    op.create_index(op.f('ix_asistencias_id'), 'asistencias', ['id'], unique=False)
    op.create_index(op.f('ix_asistencias_horario_id'), 'asistencias', ['horario_id'], unique=False)
    op.create_index(op.f('ix_asistencias_fecha'), 'asistencias', ['fecha'], unique=False)
    op.create_table('turnos',
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hora_inicio', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('hora_fin', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('turnos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='turnos_pkey'),
    sa.UniqueConstraint('nombre', name='turnos_nombre_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_turnos_id'), 'turnos', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', postgresql.ENUM('TARDANZA', 'AUSENCIA', 'ALERTA', 'JUSTIFICACION', 'APROBACION', 'RECHAZO', 'RECORDATORIO', 'SISTEMA', 'EXCESO_JORNADA', 'INCUMPLIMIENTO_JORNADA', name='tiponotificacion'), autoincrement=False, nullable=False),
    sa.Column('prioridad', postgresql.ENUM('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridadnotificacion'), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('mensaje', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('datos_adicionales', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('leida', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fecha_lectura', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('email_enviado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fecha_envio_email', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('accion_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('accion_texto', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('expira_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notificaciones_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notificaciones_pkey'))
    )
    op.create_index(op.f('ix_notificaciones_user_id'), 'notificaciones', ['user_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_tipo'), 'notificaciones', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('codigo_user', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('huella', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='users_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_codigo_user'), 'users', ['codigo_user'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('es_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('puede_aprobar', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('puede_ver_reportes', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('puede_gestionar_usuarios', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('horarios',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('turno_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dia_semana', postgresql.ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='diasemana'), autoincrement=False, nullable=False),
    sa.Column('hora_entrada', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('hora_salida', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('horas_requeridas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tolerancia_entrada', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tolerancia_salida', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], name=op.f('horarios_turno_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('horarios_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('horarios_pkey')),
    sa.UniqueConstraint('user_id', 'dia_semana', 'turno_id', name=op.f('uq_user_dia_turno'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_horarios_user_id'), 'horarios', ['user_id'], unique=False)
    op.create_index(op.f('ix_horarios_turno_id'), 'horarios', ['turno_id'], unique=False)
    op.create_index(op.f('ix_horarios_id'), 'horarios', ['id'], unique=False)
    op.create_table('justificaciones',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('tipo', postgresql.ENUM('MEDICA', 'PERSONAL', 'FAMILIAR', 'ACADEMICA', 'PERMISO_AUTORIZADO', 'VACACIONES', 'LICENCIA', 'OTRO', name='tipojustificacion'), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('estado', postgresql.ENUM('PENDIENTE', 'APROBADA', 'RECHAZADA', 'CANCELADA', name='estadojustificacion'), autoincrement=False, nullable=False),
    sa.Column('aprobado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_revision', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentario_revisor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('documento_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('notificacion_enviada', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por'], ['users.id'], name=op.f('justificaciones_aprobado_por_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('justificaciones_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('justificaciones_pkey'))
    )
    op.create_index(op.f('ix_justificaciones_user_id'), 'justificaciones', ['user_id'], unique=False)
    op.create_index(op.f('ix_justificaciones_id'), 'justificaciones', ['id'], unique=False)
    # ### end Alembic commands ###
