"""Add facial_recognize field to User model

Revision ID: 94b2dffee55f
Revises: 007_drop_old_horarios_constraint
Create Date: 2025-11-25 09:02:03.914307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94b2dffee55f'
down_revision = '007_drop_old_horarios_constraint'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facial_recognize', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('users', 'facial_recognize', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'facial_recognize')
    # ### end Alembic commands ###
